version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Build Stage
          command: |
            npm i
            npm run lint
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Test Stage
          command: |
            npm i
            npm run test
  analyse:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Analyse Stage
          command: |
            npm i
            npm audit

workflows:
  run_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyse:
          requires:
            - test

